package de.labystudio.labymod;

import de.labystudio.utils.Color;

public class ModSettings
{
    public String color1 = "" + Color.c + "e";
    public String color2 = "" + Color.c + "7";
    public String color3 = "" + Color.c + "f";
    public String color4 = "" + Color.c + "f";
    public String color5 = "" + Color.c + "4";
    public String color6 = "" + Color.c + "1";
    public String color7 = "" + Color.c + "3";
    public String color8 = "" + Color.c + "c";
    public String color9 = "" + Color.c + "4";
    public String color10 = "" + Color.c + "7";
    public int layout = 2;
    public int size = 50;
    public String showListOf = "MC-HG";
    public String last_Server = "";
    public int hud = 4;
    public boolean gui = true;
    public boolean box = false;
    public boolean potionEffects = true;
    public boolean showPing = false;
    public boolean bold = false;
    public boolean underline = false;
    public boolean italic = false;
    public boolean lavaTime = false;
    public boolean showFPS = false;
    public boolean extraChat = false;
    public boolean showCoords = false;
    public boolean oldDMG = true;
    public boolean oldHearts = true;
    public boolean oldBow = true;
    public boolean oldSword = true;
    public boolean oldBlockhit = true;
    public int truncateCoords = 0;
    public boolean tabPing = false;
    public boolean oldFishing = true;
    public boolean infoInMenu = true;
    public boolean smoothFPS = false;
    public int potionsize = 0;
    public boolean betterRefresh = false;
    public boolean foodSaturation = false;
    public boolean armorRating = false;
    public String motd = "";
    public int showSettingsFriend = 0;
    public boolean showConntectedIP = true;
    public boolean alertsPlayingOn = false;
    public boolean playSounds = true;
    public byte onlineStatus = 0;
    public boolean directConnectInfo = false;
    public boolean showMyName = false;
    public boolean afkTimer = false;
    public boolean showOnlineFriends = false;
    public boolean oldTablist = false;
    public boolean guiPositionRight = false;
    public boolean onlineFriendsPositionOnTop = true;
    public boolean confirmDisconnect = false;
    public boolean hideMod = false;
    public boolean capes = true;
    public boolean showBossBar = true;
    public boolean smoothScroll = false;
    public boolean teamSpeak = false;
    public boolean brawl = false;
    public boolean tags = true;
    public boolean teamSpakIngame = false;
    public boolean fLayoutNumber = false;
    public boolean fLayoutDirection = false;
    public boolean fLayoutXAndZ = false;
    public boolean teamSpakIngameClients = false;
    public boolean radarCoordinate = false;
    public boolean radarDirection = false;
    public boolean alertsTeamSpeak = true;
    public boolean alertsChat = true;
    public boolean showServerIP = false;
    public boolean gameBrawl = true;
    public boolean gameTimolia = true;
    public boolean gamePlayMinity = true;
    public boolean showNickname = true;
    public boolean gameGommeHD = true;
    public boolean showOnlinePlayers = false;
    public boolean speedFOV = true;
    public boolean miniGames = false;
    public boolean gommePosLeft = true;
    public boolean showKills = false;
    public boolean showBWTimer = true;
    public boolean showBWTeams = false;
    public boolean autoText = false;
    public boolean chatFilter = false;
    public boolean oldSneak = false;
    public boolean autoLeave = false;
    public boolean ignoreRequests = false;
    public boolean oldBlockBuild = true;
    public boolean background = true;
    public boolean donator = false;
    public boolean showClock = false;
    public boolean logomode = false;
    public boolean quickPlay = false;
    public boolean stopWatch = false;
    public boolean armorHudPositionOnTop = false;
    public boolean leftHand = false;
    public boolean teamSpeakAlertTypeChat = true;
    public boolean chatAlertType = false;
    public boolean clickTest = false;
    public boolean chatPositionRight = true;
    public boolean leftBow = false;
    public boolean showArrow = false;
    public boolean mojangStatus = true;
    public boolean mojangStatusChat = false;
    public boolean spotfiyTrack = false;
    public boolean showBiome = false;
    public boolean cosmetics = true;
    public boolean gameHiveMC = true;
    public boolean hiveAutoScramble = false;
    public boolean oldInventory = true;
    public boolean twelveHourClock = true;
    public int colorR;
    public int colorG;
    public int colorB;
    public boolean cosmeticsWolfTail;
    public boolean cosmeticsWings;
    public boolean cosmeticsOcelot;
    public boolean cosmeticsDeadmau;
    public boolean cosmeticsBlaze;
    public boolean cosmeticsWither;
    public boolean cosmeticsHat;
    public int cosmeticsTool;
    public boolean cosmeticsHalo;
    public int wingsScale = 25;
    public boolean showDate;
    public boolean showLiveTicker = true;
    public boolean controller = false;
    public boolean skyblock = true;
    public int month = -1;
    public boolean nameHistory = true;
    public boolean gommeBedTimer = false;
    public boolean gommeBeaconTimer = false;
    public boolean api = true;
    public boolean mineconParticle = true;
    public boolean fastChat = false;
    public boolean memory = false;
}
